name: Generate version

on:
  workflow_dispatch:
    inputs:
      version:
        description: New version
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - prerelease

jobs:
  generate-version:
    name: Create new version ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: 'npm'

      - if: github.event.inputs.version == 'prerelease'
        name: Generate new preversion
        run: npm version ${{ github.event.inputs.version }} --preid=beta

      - if: github.event.inputs.version != 'prerelease'
        name: Generate new version
        run: npm version ${{ github.event.inputs.version }}

      - name: Push new version tag
        run: git push origin master --tags

      - name: Create changelog
        uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: '^v?\d+\.\d+\.\d+/i'
          commit-template: '- {title} ({hash})'
          template: |
            ### Changelog

            {commits}

            {range}
