name: Generate version

on:
  workflow_dispatch:
    inputs:
      version:
        description: New version
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease

jobs:
  generate-version:
    name: Create new version ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: 'npm'

      - name: Setup Git user
        uses: fregante/setup-git-user@v2

      - name: Generate new version
        id: generate-version
        run: |
          npm version ${{ github.event.inputs.version }} --preid=beta
          echo node -p "require('./package.json').version" >> $NEW_VERSION

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Bump ${{ steps.generate-version.outputs.NEW_VERSION }}
          branch: bump/${{ steps.generate-version.outputs.NEW_VERSION }}
