name: Close inactives issues

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lock-threads:
    runs-on: ubuntu-latest

    steps:
      - uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          issue-lock-inactive-days: '180'
