name: Publish tag

on:
  push:
    branches:
      - master
    paths:
      - package.json
      - package-lock.json
  pull_request_target:
    branches:
      - master
    types:
      - closed

jobs:
  publish-tag:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: 'npm'

      - name: Setup Git user
        uses: fregante/setup-git-user@v2

      - name: Get version
        id: get-version
        run: |
          echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Publish tag
        run: |
          git tag ${{ steps.get-version.outputs.NEW_VERSION }}
          git push --tags
