name: update-coverage

on:
  push:
    branches:
      - master

jobs:
  update-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: 'yarn'

      - name: Install Packages
        run: yarn install --immutable

      - name: Run tests
        run: yarn run test

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
